### ISSUE TITLE
Add fonts to project

### ISSUE THREAD

**Issue by AndreyDmitriev39r** [Dorfieeee/fcc-local-weather#12]
By default, tailwind has only 3 classes for applying font-family.

We should figure out what fonts we will use for project and more custom classes for fonts.

Two possible options:

- use default fonts like `Helvetica` or `Tahoma` or `Verdana` etc. This will require just some changes in tailwind config file.

- use downloaded fonts, like Google fonts. This will require additional step for importing fonts.

I will leave the above choice and choice of particular fonts to the assignee.

Good starting point for research:

https://tailwindcss.com/docs/font-family

For completing this issue, add couple of custom classes for font-family and apply it to 2 or 3 html elements on our page.
In PR original post brifly specify what fonts did you add and where on the page it was applied.

This issue is not about choosing the whole font scheme for app, we just need something to start with, and all the fonts will be easy to fix/edit/add in the future.

**Comment by Sakoutecher** [comment]
Hello @AndreyDmitriev39r 
Could i try this ? I will choice the first options with 'Helvetica', 'Tahoma' and 'Verdana'.
I will add those fonts to the tailwind config and use it on 3 html element.
I will notify them in the PR.

**Comment by Dorfieeee** [comment]
@Sakoutecher hey!

You can try some Google fonts as well and use 'Helvetica' | 'Tahoma' | 'Verdana' as fallback fonts.
We want to make it look pretty! :]

**Comment by Sakoutecher** [comment]
No problem, could you assign me this ?

**Comment by Sakoutecher** [comment]
Hello, you can now look to my PR.

Have a good day ! 👋
