### ISSUE TITLE
Create a basic weather dashboard layout for mobile devices

### ISSUE THREAD

**Issue by Dorfieeee** [Dorfieeee/fcc-local-weather#2]
Create a wireframe for this dashboard in `index.html` by using either flexbox, grid, or combination of both.
You need to use Tailwind utility classes.

> ui vision

![Image](https://user-images.githubusercontent.com/65303812/221537235-aa5e5821-0ba6-409d-bc6d-6b9ddbd3d75d.png)

> wireframe desktop

<img width="772" alt="image" src="https://user-images.githubusercontent.com/65303812/221692184-ef9e99a2-dfd6-48af-bbbd-e0d7fd2673a5.png">

> wireframe mobile

![image](https://user-images.githubusercontent.com/65303812/221880088-c9bd03df-24e1-4469-a849-19391a127f56.png)

**Comment by AndreyDmitriev39r** [comment]
I will work on this one as soon as number 1 issue is resolved. Could take a while, since I have 0 tailwind experience.

**Comment by AndreyDmitriev39r** [comment]
I am comfortable with flex, with grid - less experience, but also fine.
Main fun will be figuring out what utility classes to use.

**Comment by Dorfieeee** [comment]
I've changed this issue so you need to start a layout for mobile devices.

**Comment by Dorfieeee** [comment]
I think we should all be involved in building the layout. I am assigning the rest of the team 👯
